document.getElementById('year').textContent = new Date().getFullYear();

const dimensionFormulas = {
    "acceleration": "[L][T<sup>-2</sup>]",
    "activity (of a radioactive source)": "[T<sup>-1</sup>]",
    "angular acceleration": "[T<sup>-2</sup>]",
    "angular momentum": "[M][L<sup>2</sup>][T<sup>-1</sup>]",
    "angular velocity": "[T<sup>-1</sup>]",
    "area": "[L<sup>2</sup>]",
    "Boltzmann constant": "[M][L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "capacitance": "[M<sup>-1</sup>][L<sup>-2</sup>][T<sup>4</sup>][I<sup>2</sup>]",
    "Coulomb constant": "[M][L<sup>3</sup>][T<sup>-4</sup>][I<sup>-2</sup>]",
    "density": "[M][L<sup>-3</sup>]",
    "dose equivalent": "[L<sup>2</sup>][T<sup>-2</sup>]",
    "dynamic viscosity": "[M][L<sup>-1</sup>][T<sup>-1</sup>]",
    "electric charge": "[T][I]",
    "electric current": "[I]",
    "electric dipole moment": "[L][I][T]",
    "electric field": "[M][L][T<sup>-3</sup>][I<sup>-1</sup>]",
    "electric flux": "[M][L<sup>3</sup>][T<sup>-3</sup>][I<sup>-1</sup>]",
    "electric potential": "[M][L<sup>2</sup>][T<sup>-3</sup>][I<sup>-1</sup>]",
    "electric resistance": "[M][L<sup>2</sup>][T<sup>-3</sup>][I<sup>-2</sup>]",
    "electric displacement field": "[L<sup>-2</sup>][T][I]",
    "electrical capacitance": "[M<sup>-1</sup>][L<sup>-2</sup>][T<sup>4</sup>][I<sup>2</sup>]",
    "electrical conductance": "[M<sup>-1</sup>][L<sup>-2</sup>][T<sup>3</sup>][I<sup>2</sup>]",
    "electrical inductance": "[M][L<sup>2</sup>][T<sup>-2</sup>][I<sup>-2</sup>]",
    "elementary charge": "[T][I]",
    "energy": "[M][L<sup>2</sup>][T<sup>-2</sup>]",
    "enthalpy": "[M][L<sup>2</sup>][T<sup>-2</sup>]",
    "entropy": "[M][L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "Faraday constant": "[T][I][N<sup>-1</sup>]",
    "force": "[M][L][T<sup>-2</sup>]",
    "frequency": "[T<sup>-1</sup>]",
    "gas constant": "[M][L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "Gibbs free energy": "[M][L<sup>2</sup>][T<sup>-2</sup>]",
    "heat capacity": "[M][L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "Helmholtz free energy": "[M][L<sup>2</sup>][T<sup>-2</sup>]",
    "illuminance": "[J][T<sup>-1</sup>][L<sup>-2</sup>]",
    "inductance": "[M][L<sup>2</sup>][T<sup>-2</sup>][I<sup>-2</sup>]",
    "irradiance": "[M][T<sup>-3</sup>]",
    "kinematic viscosity": "[L<sup>2</sup>][T<sup>-1</sup>]",
    "length": "[L]",
    "luminous flux": "[J][T]",
    "luminous intensity": "[J]",
    "magnetic field": "[M][T<sup>-2</sup>][I<sup>-1</sup>]",
    "magnetic field strength": "[L<sup>-1</sup>][I]",
    "magnetic flux": "[M][L<sup>2</sup>][T<sup>-2</sup>][I<sup>-1</sup>]",
    "magnetic flux density": "[M][T<sup>-2</sup>][I<sup>-1</sup>]",
    "mass": "[M]",
    "momentum": "[M][L][T<sup>-1</sup>]",
    "permeability": "[M][L][T<sup>-2</sup>][I<sup>-2</sup>]",
    "permittivity": "[M<sup>-1</sup>][L<sup>-3</sup>][T<sup>4</sup>][I<sup>2</sup>]",
    "Planck constant": "[M][L<sup>2</sup>][T<sup>-1</sup>]",
    "plane angle": "[1]",
    "power": "[M][L<sup>2</sup>][T<sup>-3</sup>]",
    "pressure": "[M][L<sup>-1</sup>][T<sup>-2</sup>]",
    "radiant flux": "[M][L<sup>2</sup>][T<sup>-3</sup>]",
    "radiant intensity": "[M][T<sup>-3</sup>]",
    "resistance": "[M][L<sup>2</sup>][T<sup>-3</sup>][I<sup>-2</sup>]",
    "solid angle": "[1]",
    "specific entropy": "[L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "specific heat": "[L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "specific volume": "[L<sup>3</sup>][M<sup>-1</sup>]",
    "spectral irradiance": "[M][L<sup>-1</sup>][T<sup>-3</sup>]",
    "spectral power": "[M][L<sup>2</sup>][T<sup>-3</sup>]",
    "spectral radiant exitance": "[M][T<sup>-3</sup>][L<sup>-1</sup>]",
    "spectral radiance": "[M][L<sup>-2</sup>][T<sup>-3</sup>]",
    "spectral intensity": "[M][L<sup>2</sup>][T<sup>-3</sup>][L<sup>-1</sup>]",
    "specific entropy": "[L<sup>2</sup>][T<sup>-2</sup>][K<sup>-1</sup>]",
    "Stefan-Boltzmann constant": "[M][T<sup>-3</sup>][K<sup>-4</sup>]",
    "surface tension": "[M][T<sup>-2</sup>]",
    "thermal conductivity": "[M][L][T<sup>-3</sup>][K<sup>-1</sup>]",
    "thermal diffusivity": "[L<sup>2</sup>][T<sup>-1</sup>]",
    "thermal efficiency": "[1]",
    "thermal expansion": "[L<sup>-1</sup>][K<sup>-1</sup>]",
    "thermal insulance": "[M<sup>-1</sup>][L<sup>-1</sup>][T<sup>3</sup>][K]",
    "thermal resistance": "[M<sup>-1</sup>][L<sup>-1</sup>][T<sup>3</sup>][K]",
    "time": "[T]",
    "universal gravitation constant": "[M<sup>-1</sup>][L<sup>3</sup>][T<sup>-2</sup>]",
    "velocity": "[L][T<sup>-1</sup>]",
    "voltage": "[M][L<sup>2</sup>][T<sup>-3</sup>][I<sup>-1</sup>]",
    "volume": "[L<sup>3</sup>]",
    "wavelength": "[L]",
    "work": "[M][L<sup>2</sup>][T<sup>-2</sup>]",
    "wavelength": "[L]",
    "weight": "[M][L][T<sup>-2</sup>]",
    "wind speed": "[L][T<sup>-1</sup>]",
    "wave number": "[L<sup>-1</sup>]",
}

function calculateDimension() {
    const quantity = document.getElementById('quantity').value.trim().toLowerCase();
    const resultDiv = document.getElementById('result');
    const formula = dimensionFormulas[quantity];

    if (formula) {
        resultDiv.innerHTML = `The dimension formula for <strong>${quantity}</strong> is: ${formula}`;
    } else {
        resultDiv.innerHTML = `Dimension formula for <strong>${quantity}</strong> is not available.`;
    }
}
